### PR TITLE
Transferred existing user guide material

### PR DESCRIPTION
**Pull request by tobyhodges**
Addresses point 1 in #2 

A first draft of the new user guide. These are pretty much direct transfers of the existing user guide chapters, with the main additions being header info to render the carpentry-style episode pages. Also, a note encouraging minimal use of JavaScript expressions (which should make @mr-c happy 😛)

### CODE REVIEW

**Comment by mr-c** [comment]
@tobyhodges Are you ready for me to review this?

**Comment by tobyhodges** [comment]
yes please. Pretty much all new material to come in separate PRs

**Comment by tobyhodges** [comment]
you can view the rendered version at tobyhodges.github.io/user_guide

**Comment by mr-c** [comment]
Merging  -- I'll add other tweaks in other PRs

**Pull request merged**
