### PR TITLE
16-file-formats: fix output name record

### PR DESCRIPTION
**Pull request by jirikuncar**
Spotted on http://www.commonwl.org/user_guide/16-file-formats/

### CODE REVIEW

**Comment by manabuishii** [comment]
When I check this PullRequest.

I wonder this 16's sample actually using this section.

```yaml
bamstats_report:
    class: File
    path: /tmp/bamstats_report.zip
```

This pull request version

```yaml
report:
    class: File
    path: /tmp/bamstats_report.zip
```

Both are same result and always `output.txt` is created.

I think this is a result of 

```metadata_example.cwl
stdout: output.txt

outputs:
  report:
    type: stdout
    format: edam:format_1964
    label: A text file that contains a line count
```

and result of cwltool looks almost same
(`sample.yml` is using this pull request version)

```console
$ cwltool metadata_example.cwl sample.yml 
/home/manabu/.local/bin/cwltool 1.0.20180111185617
Resolved 'metadata_example.cwl' to 'file:///home/manabu/.ghq/github.com/common-workflow-language/user_guide/_includes/cwl/16-file-formats/metadata_example.cwl'
[job metadata_example.cwl] /tmp/tmpr5yd6_$ wc \
    -l \
    /tmp/tmp5exIdV/stgd76b2bc9-72c6-47bc-b1b6-ecc3689b6174/file-formats.bam > /tmp/tmpr5yd6_/output.txt
[job metadata_example.cwl] completed success
{
    "report": {
        "format": "http://edamontology.org/format_1964", 
        "checksum": "sha1$6cec3ea6fefaa506aca999b8e2d09a004c4a6358", 
        "basename": "output.txt", 
        "location": "file:///home/manabu/.ghq/github.com/common-workflow-language/user_guide/_includes/cwl/16-file-formats/output.txt", 
        "path": "/home/manabu/.ghq/github.com/common-workflow-language/user_guide/_includes/cwl/16-file-formats/output.txt", 
        "class": "File", 
        "size": 78
    }
}
Final process status is success
```

`output.txt` is

```
13698 /tmp/tmp5exIdV/stgd76b2bc9-72c6-47bc-b1b6-ecc3689b6174/file-formats.bam
```

**Comment by manabuishii** [comment]
Related to #73

**Comment by kaushik-work** [comment]
@manabuishii @jirikuncar I'm not familiar with this option - I'm assuming `sample.yml` is the input (job) file. What effect does specifying the path to an output file have? Does it govern the name and location of the output file - overriding the default location a runner puts it in? Thanks!

**Comment by mr-c** [comment]
@kaushik-work Thanks for the ping. This was a dockstore-ism that slipped in. For reasons I don't understand, the put the outputs also in the input object. That is not standard CWL.

**Pull request merged**
