### PR TITLE
Added BibTex record

### PR DESCRIPTION
**Pull request by tobyhodges**

### CODE REVIEW

**Comment by mr-c** [comment]
@tobyhodges Oh! I was going to do this, but then I noticed that Zenodo has a BibTex exporter: https://zenodo.org/record/840130 (under "Cite As"). If we refer to that we won't have to keep the bibtex up to date..

**Comment by tobyhodges** [comment]
That is true, but by default the BibTex record includes all of the contributors to the repo, ordered by number of commits. This means that it includes the SWC folks who developed the template. Do you think we can override that in .zenodo.json too?

**Comment by mr-c** [comment]
@tobyhodges the "v2" (actually from the `v0.3` tag) doesn't have that problem: https://zenodo.org/record/840663

**Comment by tobyhodges** [comment]
ok, fair enough then!

**Pull request closed without merging**
