### PR TITLE
Update basic-concepts.md

### PR DESCRIPTION
**Pull request by khaiyra**
matched the sequence of the types of processes listed.

### CODE REVIEW

**Comment by swzCuroverse** [comment]
@tetron this is set to go.

**Review by kinow — APPROVED** [review]

**Comment by tetron** [comment]
There's a merge conflict

**Comment by khaiyra** [comment]
I guess because my branch wasn't up-to-date when I pulled a request. Let me try that again.

**Comment by kinow** [comment]
@khaiyra it would be better to start using the same pull request. This way the reviews are kept in a single place, and it's easier for reviewers as they won't mistaken the other PR for a duplicate task (which happens when we have a large group of devs working on the same project :slightly_smiling_face: ), cc @swzCuroverse

**Comment by khaiyra** [comment]
ooh my bad, now I've learnt this and would put into practice moving forward. Thanks @kinow for pointing that out and sorry for any inconveniences🙂

**Pull request closed without merging**
