### PR TITLE
Changing command to create a virtual environment

### PR DESCRIPTION
**Pull request by dear-ore**
`python3 -m venv venv` instead of `python -m venv venv`

### CODE REVIEW

**Comment by Fienne** [comment]
I wish to say that specifying the python version is only necessary if the normal `python -m venv venv` doesn't work

**Review by mr-c — APPROVED** [review]
Thank you @dear-ore ; in the future it would have been nicer for the maintainers and reviewer if this and #312 were in the same PR since they are related; or even better if #310 was re-used. 

I think you've been making your changes via the web interface. That's nice for single file changes, but you should learn how to edit the files locally. Perhaps some of the other Outreachy applicants can suggest their favorite tutorials for git & GitHub usage.

**Comment by dear-ore** [comment]
Thank you @mr-c. Is building the documentation locally the best way to contribute and make changes?
And I'm sorry for all the stress caused by my many PRs.

**Comment by mr-c** [comment]
It is okay.

Yes, following https://github.com/common-workflow-language/user_guide/blob/main/CONTRIBUTING.md

**Comment by dear-ore** [comment]
Thank you @mr-c

**Pull request merged**
