### PR TITLE
Patch MyST to keep the context needed to translate Markdown files

### LINKED ISSUE #368: Convert Md to ReST to work around issue with translations
The following files also have internal links that need converting to ReST.

- [ ]  src/index.md
- [ ]  src/topics/additional-arguments-and-parameters.md
- [ ] src/topics/best-practices.md
- [ ] src/topics/custom-types.md
- [ ] src/topics/expressions.md
- [ ] src/topics/file-formats.md
- [ ] src/topics/metadata-and-authorship.md
- [ ] src/topics/specifying-software-requirements.md
- [ ] src/topics/using-containers.md
- [ ] src/topics/yaml-guide.md

Conversion process:

(1) Convert markdown to rst
```
pandoc --from markdown --to rst --reference-links src/topics/additional-arguments-and-parameters.md \
    > src/topics/additional-arguments-and-parameters.rst
```

(2) Change links to be named links (see description below)
```
vim src/topics/additional-arguments-and-parameters.rst # edit to change the links to be named links
git add src/topics/additional-arguments-and-parameters.rst
git rm src/topics/additional-arguments-and-parameters.md
```

Note: the links in the output from pandoc need to be adjusted, even with `--reference-links`. This is the vim step above, and can be done with any editor.

Change the links from this style:

``` rst
All Common Workflow Language project instructional material and changes
to the structure are also made available under the `Creative Commons
Attribution license`_. The following is a human-readable summary of (and
not a substitute for) the `full legal text of the CC BY 4.0 license`_.

.. _Creative Commons Attribution license: https://creativecommons.org/licenses/by/4.0/
.. _full legal text of the CC BY 4.0 license: https://creativecommons.org/licenses/by/4.0/legalcode
```
to

``` rst
All Common Workflow Language project instructional material and changes
to the structure are also made available under the `Creative Commons
Attribution license <cc-by-human_>`_. The following is a human-readable summary of (and
not a substitute for) the `full legal text of the CC BY 4.0 license <cc-by-legal_>`_.

.. _cc-by-human: https://creativecommons.org/licenses/by/4.0/
.. _cc-by-legal: https://creativecommons.org/licenses/by/4.0/legalcode
```

That way the links have a target (cc-by-human) independent of the link text, which will need to change in the translations.

(3)
Edit any references to `additional-arguments-and-parameters.md` to refer to `additional-arguments-and-parameters.rst`
`git grep -l additional-arguments-and-parameters.md -- src | xargs sed -i 's/additional-arguments-and-parameters.md/additional-arguments-and-parameters.rst`
(if the file name is `index.md` then be careful, as there are many `index.md` files)

### PR DESCRIPTION
**Pull request by kinow**
Fixes #368 

This fixes the build and produces the expected Markdown.

- https://github.com/common-workflow-language/user_guide/issues/91#issuecomment-1403786635
- https://github.com/executablebooks/MyST-Parser/issues/690

The diff applied to MyST (created on the MyST parser git clone, posting here to show how much I had to change - bugs of few lines are always the ones that take longer to be solved):

```diff
diff --git a/myst_parser/parsers/sphinx_.py b/myst_parser/parsers/sphinx_.py
index 94d5aef..2be1d77 100644
--- a/myst_parser/parsers/sphinx_.py
+++ b/myst_parser/parsers/sphinx_.py
@@ -66,5 +66,15 @@ class MystParser(SphinxParser):
                 config = merge_file_level(config, topmatter, warning)
 
         parser = create_md_parser(config, SphinxRenderer)
+        # TODO: In the first pass, the call above will use MarkdownIt over the whole document,
+        #       populating the ``.md_env`` correctly. Over the next passes, from transforms as
+        #       ``sphinx.transforms.i18n.Locale`` it will create a blank new document, as well
+        #       as a new MarkdownIT parser but using just the Docutils document that is being
+        #       translated. As a result of this, the translation has no reference-links, and it
+        #       gives you the translation without resolving the links. Here we just re-use the
+        #       ``md_env`` dictionary that contains the ``.references`` populated in the first
+        #       pass, fixing i18n with MyST Parser.
+        env = {} if not hasattr(document.settings, 'md_env') else document.settings.md_env
         parser.options["document"] = document
-        parser.render(inputstring)
+        parser.render(inputstring, env)
+        document.settings.md_env = parser.renderer.md_env
```

I will share in their issue and see if they can come up with a better solution. Not sure whether we should use this patched version or start moving things to reST. On one hand this works but has the risk of getting out of sync with MyST (even though the diff is minimal), while on the other migrating everything to reST is a major effort.

Anyway, now at least we know what's wrong in MyST and I can stop thinking about this (interesting!) bug :bug: :lady_beetle: 

image

Cheers
-Bruno

p.s.: I believe MyST will fix this issue soon-ish, as it's used in PyData and other Jupyter projects, but if there's haste in translating, at least we have a possible workaround....

### CODE REVIEW

**Comment by kinow** [comment]
(fixing the rtd build):

```
ModuleNotFoundError: No module named 'myst_parser.warnings_'
```

**Comment by kinow** [comment]
(had patched MyST's `master` branch :grimacing: changed to the `0.18.1` version we are using and applied to patch again :crossed_fingers: )

**Review by mr-c — CHANGES_REQUESTED** [review]
Wow! Thank you for this @kinow !

I'm seeing lots of warnings that the default `make html` makes into errors (but readthedocs does not)

```
/home/docs/checkouts/readthedocs.org/user_builds/common-workflow-languageuser-guide/checkouts/370/src/topics/expressions.md:114: WARNING: Duplicate reference definition: FILE-PROP [myst.ref]
/home/docs/checkouts/readthedocs.org/user_builds/common-workflow-languageuser-guide/checkouts/370/src/topics/file-formats.md:114: WARNING: Duplicate reference definition: FILE-PROP [myst.ref]
/home/docs/checkouts/readthedocs.org/user_builds/common-workflow-languageuser-guide/checkouts/370/src/topics/index.md:114: WARNING: Duplicate reference definition: FILE-PROP [myst.ref]
/home/docs/checkouts/readthedocs.org/user_builds/common-workflow-languageuser-guide/checkouts/370/src/topics/inputs.md:114: WARNING: Duplicate reference definition: FILE-PROP [myst.ref]
/home/docs/checkouts/readthedocs.org/user_builds/common-workflow-languageuser-guide/checkouts/370/src/topics/metadata-and-authorship.md:114: WARNING: Duplicate reference definition: FILE-PROP [myst.ref]
/home/docs/checkouts/readthedocs.org/user_builds/common-workflow-languageuser-guide/checkouts/370/src/topics/operations.md:114: WARNING: Duplicate reference definition: FILE-PROP [myst.ref]
/home/docs/checkouts/readthedocs.org/user_builds/common-workflow-languageuser-guide/checkouts/370/src/topics/outputs.md:114: WARNING: Duplicate reference definition: FILE-PROP [myst.ref]
/home/docs/checkouts/readthedocs.org/user_builds/common-workflow-languageuser-guide/checkouts/370/src/topics/parameter-references.md:114: WARNING: Duplicate reference definition: FILE-PROP [myst.ref]
/home/docs/checkouts/readthedocs.org/user_builds/common-workflow-languageuser-guide/checkouts/370/src/topics/requirements-and-hints.md:114: WARNING: Duplicate reference definition: FILE-PROP [myst.ref]
/home/docs/checkouts/readthedocs.org/user_builds/common-workflow-languageuser-guide/checkouts/370/src/topics/specifying-software-requirements.md:114: WARNING: Duplicate reference definition: FILE-PROP [myst.ref]
/home/docs/checkouts/readthedocs.org/user_builds/common-workflow-languageuser-guide/checkouts/370/src/topics/specifying-software-requirements.md:41: WARNING: Duplicate reference definition: SCICRUNCH [myst.ref]
/home/docs/checkouts/readthedocs.org/user_builds/common-workflow-languageuser-guide/checkouts/370/src/topics/staging-input-files.md:114: WARNING: Duplicate reference definition: FILE-PROP [myst.ref]
/home/docs/checkouts/readthedocs.org/user_builds/common-workflow-languageuser-guide/checkouts/370/src/topics/staging-input-files.md:41: WARNING: Duplicate reference definition: SCICRUNCH [myst.ref]
/home/docs/checkouts/readthedocs.org/user_builds/common-workflow-languageuser-guide/checkouts/370/src/topics/troubleshooting.md:114: WARNING: Duplicate reference definition: FILE-PROP [myst.ref]
/home/docs/checkouts/readthedocs.org/user_builds/common-workflow-languageuser-guide/checkouts/370/src/topics/troubleshooting.md:41: WARNING: Duplicate reference definition: SCICRUNCH [myst.ref]
/home/docs/checkouts/readthedocs.org/user_builds/common-workflow-languageuser-guide/checkouts/370/src/topics/using-containers.md:114: WARNING: Duplicate reference definition: FILE-PROP [myst.ref]
/home/docs/checkouts/readthedocs.org/user_builds/common-workflow-languageuser-guide/checkouts/370/src/topics/using-containers.md:41: WARNING: Duplicate reference definition: SCICRUNCH [myst.ref]
/home/docs/checkouts/readthedocs.org/user_builds/common-workflow-languageuser-guide/checkouts/370/src/topics/workflows.md:114: WARNING: Duplicate reference definition: FILE-PROP [myst.ref]
/home/docs/checkouts/readthedocs.org/user_builds/common-workflow-languageuser-guide/checkouts/370/src/topics/workflows.md:41: WARNING: Duplicate reference definition: SCICRUNCH [myst.ref]
/home/docs/checkouts/readthedocs.org/user_builds/common-workflow-languageuser-guide/checkouts/370/src/topics/yaml-guide.md:114: WARNING: Duplicate reference definition: FILE-PROP [myst.ref]
/home/docs/checkouts/readthedocs.org/user_builds/common-workflow-languageuser-guide/checkouts/370/src/topics/yaml-guide.md:41: WARNING: Duplicate reference definition: SCICRUNCH [myst.ref]
/home/docs/checkouts/readthedocs.org/user_builds/common-workflow-languageuser-guide/checkouts/370/src/tutorials.md:114: WARNING: Duplicate reference definition: FILE-PROP [myst.ref]
/home/docs/checkouts/readthedocs.org/user_builds/common-workflow-languageuser-guide/checkouts/370/src/tutorials.md:41: WARNING: Duplicate reference definition: SCICRUNCH [myst.ref]
```
https://readthedocs.org/projects/common-workflow-languageuser-guide/builds/19289547/

**Comment by mr-c** [comment]
@kinow I added commits to revert the LICENSE `.md` to `.rst` conversion

**Review by mr-c — APPROVED** [review]
Okay, we can fix the warnings later

**Pull request merged**
