### PR TITLE
Update basic-concepts.md

### PR DESCRIPTION
**Pull request by bamiwoaluko**
corrected typos, corrected punctuations, rephrased  sentences, added a link where required

### CODE REVIEW

**Review by kinow — COMMENTED** [review]
Git conflicts

**Comment by bamiwoaluko** [comment]
> 

oh? what do i do to resolve the issue?

**Comment by kinow** [comment]
> > 
> 
> oh? what do i do to resolve the issue?

A reviewer may be able to resolve it for you, but it's easier if you are able to fix it. It's also a good opportunity for learning git :slightly_smiling_face: 

Have a read and see if you are able to use the GitHub UI to resolve the conflicts: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github

Or if you prefer the command-line: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line

-Bruno

**Comment by bamiwoaluko** [comment]
> 

i believe i have resolved the conflicts already

**Review by tetron — APPROVED** [review]

**Pull request merged**
