### PR TITLE
fix broken link

### LINKED ISSUE #264: Broken Link
The "cite" link on the user guide page footer is broken. It links to a 404 page
Below are images of how it looks.
Group 1 (6)
Screenshot from 2022-10-10 23-13-15 1

### PR DESCRIPTION
**Pull request by Fienne**
fixes #264

### CODE REVIEW

**Review by kinow — APPROVED** [review]
Great catch!

There's also a tool that could be used to verify all links: https://validator.w3.org/checklink

There's also a Sphinx built-in tool called `linkcheck`. @swzCuroverse, @mr-c I'll create an issue for this. We don't really need to use it, we can use the W3 checklink tool periodically too, or instruct people wanting to collaborate to check for links, etc.

Here's an example of how to run the linkcheck, which finishes in under 10 seconds for my environment: `sphinx-build -b linkcheck src _build/`

It found a few broken links :grimacing: Sorry for digressing here, +1 on merging this one. Thanks @Fienne !

**Comment by Fienne** [comment]
> Great catch!
> 
> There's also a tool that could be used to verify all links: https://validator.w3.org/checklink
> 
> There's also a Sphinx built-in tool called `linkcheck`. @swzCuroverse, @mr-c I'll create an issue for this. We don't really need to use it, we can use the W3 checklink tool periodically too, or instruct people wanting to collaborate to check for links, etc.
> 
> Here's an example of how to run the linkcheck, which finishes in under 10 seconds for my environment: `sphinx-build -b linkcheck src _build/`
> 
> It found a few broken links grimacing Sorry for digressing here, +1 on merging this one. Thanks @Fienne !

I don't think you digressed here, you instead gave me a new way to fix issues. Thank you for merging this!😊

**Comment by swzCuroverse** [comment]
@kinow and @Fienne should we close this or keep it up until merged with release?

**Comment by Fienne** [comment]
I think we should close this since @kinow opened an issue for the broken link checker.

**Comment by kinow** [comment]
> @kinow and @Fienne should we close this or keep it up until merged with release?

I think this one can be merged to fixthe citation link and then if someone is interested they can work on #267

**Pull request merged**
