### PR TITLE
Convert faq headings to questions

### LINKED ISSUE #348: FAQ entries should be questions
Or we should rename the sections

(moved from https://github.com/common-workflow-language/user_guide/pull/337#discussion_r1010576115 )

### PR DESCRIPTION
**Pull request by Fienne**
Hi @swzCuroverse here's the pull request we agreed I'd open. Please let me know if I'm doing it correctly so I can proceed.
fixes #348

### CODE REVIEW

**Comment by swzCuroverse** [comment]
These look good so far.  Thanks!

**Comment by Fienne** [comment]
@swzCuroverse can you please have a look at this again?

**Comment by swzCuroverse** [comment]
@mr-c and @Fienne this looks ready to go.

**Comment by swzCuroverse** [comment]
Whoops. forgot to also tag @tetron

**Review by tetron — APPROVED** [review]

**Comment by swzCuroverse** [comment]
@tetron I think you have to just "re check" this?

**Pull request merged**
