### PR TITLE
cleanup & simplification

### PR DESCRIPTION
**Pull request by mr-c**
@tobyhodges feel free to propagate these stylistic changes via additional commits to this branch

### CODE REVIEW

**Comment by tobyhodges** [comment]
sadly it seems that I can't push directly to the branch. Shall I submit another PR?

**Comment by mr-c** [comment]
@tobyhodges I just tweaked some permissions, try again?

**Comment by tobyhodges** [comment]
Yeah, that's done it.

**Comment by mr-c** [comment]
Thanks @tobyhodges !

**Pull request merged**
