### PR TITLE
Recommended practices checklist

### PR DESCRIPTION
**Pull request by tobyhodges**
Based on [issue #470](https://github.com/common-workflow-language/common-workflow-language/issues/470) in the main CWL repo.

I guess that I am lacking some configuration etc to integrate the document as a true episode in the user guide. This might require some more general discussion about how the user guide should be setup and maintained?

All feedback welcome.

### CODE REVIEW

**Comment by mr-c** [comment]
Yeah, I've never setup a Carpentry style repo before. Recommendations and opinions gladly solicited

**Comment by tobyhodges** [comment]
Ok, let me have a look through their docs and I'll submit a separate PR with a first draft of the config/setup. With that in mind, if you have a moment to provide a short overview of what you hope to get from this repo, e.g. in a new issue here, that would be really helpful.

**Comment by tobyhodges** [comment]
That good practices page should render through Jekyll now.

**Comment by mr-c** [comment]
@tobyhodges Cool! Do you want to merge now, or continue refining in place?

**Comment by tobyhodges** [comment]
A few more things to change. I think that this document will make more sense listed under "_extras" in the end. The "_episodes" should be made up by the examples in the existing user guide. IMO of course.

**Comment by tobyhodges** [comment]
P.S. should I move over to Gitter for these discussions? Or stay here for better record-keeping?

**Comment by mr-c** [comment]
@tobyhodges Either works! 

`_extras` makes sense, yep

**Comment by tobyhodges** [comment]
ok, marking this one is ready now

**Pull request merged**
