### PR TITLE
Update number for each guide

### PR DESCRIPTION
**Pull request by tom-tan**
A file (or directory) names in directories `_includes/cwl` and `_episodes` have to correspond to each guide.
However, some files (for 19 and larger guide) does not correspond to the step number in user guide.

This request renames them. I also update `_includes/cwl/conformance-test.yml`.

### CODE REVIEW

**Comment by mr-c** [comment]
Does this break existing links to the user guide?

**Comment by tom-tan** [comment]
> Does this break existing links to the user guide?

Yes. I fixed the links between the guides but links from external websites are affected by this change.
For instance: 19-custom-types/index.html -> 18-custom-types/index.html

Is it possible to make a redirect pages for them?

---
IMO, using section numbers as file names make them fragile from the future changes such as reorganizing the guide. It would be nice if we can remove section numbers from the file names but it is out of scope of this request.

**Comment by stain** [comment]
I agree the number should not be part of the URI (it can be part of the markdown filename if you want, overriding the slug.)

I would suggest closing this PR, and renaming them all to be number-less.  To avoid breaking URIs we can re-add the existing names with redirects using the [jekyll-redirect-from](https://help.github.com/en/articles/redirects-on-github-pages) plugin

**Comment by tobyhodges** [comment]
The user guide is based on The Carpentries' styles repo (https://github.com/carpentries/styles). The way that things work with that infrastructure means that, if you were to remove the numbers from the filenames, the order of the sections would break - it would become alphabetical by filename.

There is an open discussion Issue about changing that https://github.com/carpentries/styles/issues/236 but, as long as the upstream setup doesn't allow this, I would recommend against changing the numbering system in this repository.

**Comment by tobyhodges** [comment]
Update: I have [submitted a PR] to carpentries/styles to allow arbitrary ordering of episodes (instead of numbering). If that gets merged, we can pull the latest changes from the template repository and get started on a more sustainable fix for this problem in the CWL UG.

**Comment by mr-c** [comment]
@tobyhodges So exciting, thank you! If that gets merged then I'll incorporate those changes here and then close this PR.

@tom-tan Thank you again for your PR and starting this conversation.

**Comment by tobyhodges** [comment]
I’ll just add that, if you want to @tom-tan, you’ll be very welcome to
submit another PR changing the episode filenames and adding the relevant
field into `_config.yml`. All of that pending the upstream PR getting
merged, of course.

**Comment by tobyhodges** [comment]
An update: since we last discussed this, a new version of Jekyll (v4.0.0) was released, which includes a field allowing the order of pages to be specified in `_config.yml`. GitHub Pages isn't yet using this latest version of Jekyll to build pages, but all the same it didn't feel worth introducing all the extra customisation into the Carpentries' lesson template to achieve this behaviour. Instead, we should simply wait for GH Pages to start using this newer version of Jekyll.

**Comment by tobyhodges** [comment]
Another update: https://github.com/carpentries/styles/pull/437 was merged, so we can now do this reordering much more easily, without waiting for GitHub Pages to adopt Jekyll v. ≥4. Specify the order of episodes in the `episode_order` field of `_config.yml` - see linked PR for more info. @tom-tan would you like to adapt this PR to use the new functionality of the template, then I think we can (finally!) merge this...

**Comment by tobyhodges** [comment]
@mr-c do you want to merge the upstream changes?

**Comment by mr-c** [comment]
@tom-tan Sure, you can review it at https://github.com/common-workflow-language/user_guide/pull/171

**Comment by swzCuroverse** [comment]
@kinow should we make a ticket for this for the new user guide format or is it not relevant anymore?

**Comment by kinow** [comment]
I think this can be closed as there are no more numbers for episodes :+1:

**Pull request closed without merging**
