### PR TITLE
Fix an example of Section7 not to use side effect

### LINKED ISSUE #37: Test for the example in CI
It would be nice if there is a CI tester (such as Travis CI) for the examples in the user guide.
Such a scheme can keep the examples runnable for each commit.

### PR DESCRIPTION
**Pull request by tom-tan**
This request partially addresses #37 and #62.

I confirmed it passes conformance tests in my local machine.

### CODE REVIEW

**Comment by tom-tan** [comment]
It fails conformance tests due in unrelated place (section 17).
I guess cwltool master introduces regressions...

**Comment by mr-c** [comment]
Ah, it was missing the `html5lib` dependency. I've fixed that in https://github.com/common-workflow-language/user_guide/pull/93

By the way, @tom-tan , can you make your future branches in this repository? That would make collaboration even easier. You have permissions to push new branches to any `common-workflow-language` repository :-)

**Comment by mr-c** [comment]
@tom-tan Thanks!

**Comment by tom-tan** [comment]
> By the way, @tom-tan , can you make your future branches in this repository?

OK, I will do that from the next PR!

**Pull request merged**
